name: Deploy Vue.js to cPanel
on:
  push:
    branches: [main]
    paths-ignore:
      - "node_modules/**"
      - "**.md"
      - "**.git*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      # Cache Node modules
      - name: Cache Node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      # Clear NPM cache and remove lock files (optional, uncomment if needed)
      # - name: Clear NPM cache and remove lock files
      #   run: |
      #     rm -rf node_modules
      #     rm -f package-lock.json
      #     npm cache clean --force

      # Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Build Vue.js application
      - name: Build Vue.js app
        run: npm run build

      # Deploy to cPanel
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          server-dir: /public_html/my-portfolio/
          # Adjust the local directory to match where your Vue.js build output is located
          local-dir: ./dist/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env
            **/.env.*
            **/tests/**
            **/.editorconfig
            **/.gitattributes
            **/.gitignore
            **/README.md
            **/package-lock.json
          dangerous-clean-slate: false
